import React from 'react';
import { AIResult } from '@/lib/aiHeuristics';
import { PlagiarismResult } from '@/lib/useContentAnalysis';
import { HiOutlineShieldCheck, HiOutlineExternalLink, HiOutlinePresentationChartBar } from 'react-icons/hi';

interface ForensicReportTemplateProps {
    docTitle: string;
    aiResult: AIResult;
    plagiarismResult: PlagiarismResult;
    reportId?: string;
    date?: string;
}

const RadialProgress = ({ percentage, color, label, status }: { percentage: number, color: string, label: string, status: string }) => {
    const radius = 36;
    const circumference = 2 * Math.PI * radius;
    const offset = circumference - (percentage / 100) * circumference;

    return (
        <div style={{ 
            display: 'flex', 
            padding: '24px', 
            borderRadius: '16px', 
            alignItems: 'center', 
            gap: '24px', 
            flex: '1',
            backgroundColor: '#ffffff', 
            border: '1px solid #f1f5f9',
            boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)'
        }}>
            <div style={{ position: 'relative', width: '96px', height: '96px', display: 'flex', alignItems: 'center', justifySelf: 'center' }}>
                <svg style={{ width: '100%', height: '100%', transform: 'rotate(-90deg)' }}>
                    <circle
                        cx="48"
                        cy="48"
                        r={radius}
                        stroke="#f1f5f9"
                        strokeWidth="8"
                        fill="transparent"
                    />
                    <circle
                        cx="48"
                        cy="48"
                        r={radius}
                        stroke={color}
                        strokeWidth="8"
                        strokeDasharray={circumference}
                        strokeDashoffset={offset}
                        strokeLinecap="round"
                        fill="transparent"
                    />
                </svg>
                <div style={{ position: 'absolute', inset: '0', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
                    <span style={{ fontSize: '20px', fontWeight: '900', color: '#1e293b' }}>{percentage}%</span>
                </div>
            </div>
            <div>
                <h4 style={{ fontSize: '14px', fontWeight: '700', marginBottom: '4px', color: '#0f172a' }}>{label}</h4>
                <p style={{ fontSize: '10px', fontWeight: '500', lineHeight: '1.5', marginBottom: '8px', color: '#64748b' }}>
                    {label === 'Similarity Score' 
                        ? 'Percentage of text matching external sources and academic databases.' 
                        : 'Probability of text being generated by AI models.'}
                </p>
                <span style={{ 
                    display: 'inline-block',
                    padding: '4px 10px', 
                    borderRadius: '4px', 
                    fontSize: '9px', 
                    fontWeight: '900', 
                    textTransform: 'uppercase', 
                    letterSpacing: '0.1em',
                    backgroundColor: percentage > 50 ? '#fef2f2' : percentage > 20 ? '#fffbeb' : '#ecfdf5',
                    color: percentage > 50 ? '#dc2626' : percentage > 20 ? '#d97706' : '#059669',
                    border: `1px solid ${percentage > 50 ? '#fee2e2' : percentage > 20 ? '#fef3c7' : '#d1fae5'}`
                }}>
                    {status}
                </span>
            </div>
        </div>
    );
};

export default function ForensicReportTemplate({ 
    docTitle, 
    aiResult, 
    plagiarismResult, 
    reportId = `SA-${Math.floor(Math.random() * 9000) + 1000}-X`,
    date = new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}: ForensicReportTemplateProps) {
    if (!aiResult || !plagiarismResult) return null;

    return (
        <div id="forensic-report-canvas" style={{ 
            minHeight: '1120px', 
            padding: '24px', 
            fontFamily: 'system-ui, -apple-system, sans-serif', 
            width: '718px', // Adjusted from 794px to 718px (190mm) to fit inside A4 margins (210mm - 20mm)
            boxSizing: 'border-box',
            marginLeft: 'auto', 
            marginRight: 'auto',
            backgroundColor: '#ffffff', 
            color: '#1e293b',
            overflow: 'hidden'
        }}>
            {/* Header */}
            <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '48px', paddingBottom: '32px', borderBottom: '1px solid #f1f5f9' }}>
                <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
                        <div style={{ width: '32px', height: '32px', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#0f172a' }}>
                            <HiOutlineShieldCheck style={{ color: '#ffffff', width: '20px', height: '20px' }} />
                        </div>
                        <span style={{ fontSize: '18px', fontWeight: '900', letterSpacing: '-0.025em', fontStyle: 'italic', color: '#0f172a' }}>ScholarAssist</span>
                    </div>
                    <h1 style={{ fontSize: '30px', fontWeight: '900', letterSpacing: '-0.05em', textTransform: 'uppercase', margin: '0', color: '#0f172a' }}>Report Analysis</h1>
                    <p style={{ fontSize: '11px', fontWeight: '700', marginTop: '8px', display: 'flex', alignItems: 'center', gap: '8px', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#94a3b8' }}>
                        Analysis: <span style={{ color: '#475569' }}>{docTitle}</span>
                    </p>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '11px', fontWeight: '700', marginBottom: '4px', letterSpacing: '0.1em', color: '#94a3b8' }}>ID: {reportId}</div>
                    <div style={{ fontSize: '14px', fontWeight: '900', color: '#0f172a' }}>{date}</div>
                </div>
            </header>

            {/* Executive Summary */}
            <section style={{ marginBottom: '48px', pageBreakInside: 'avoid' }}>
                <h3 style={{ fontSize: '11px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px', color: '#94a3b8' }}>
                    <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#0f172a' }}></span>
                    Executive Summary
                </h3>
                <div style={{ display: 'flex', gap: '24px' }}>
                    <RadialProgress 
                        percentage={plagiarismResult.score} 
                        color={plagiarismResult.score > 40 ? '#ef4444' : '#f59e0b'} 
                        label="Similarity Score"
                        status={plagiarismResult.score > 40 ? 'Action Required' : plagiarismResult.score > 15 ? 'Moderate Match' : 'Normal'}
                    />
                    <RadialProgress 
                        percentage={aiResult.score} 
                        color={aiResult.score > 40 ? '#f97316' : '#f59e0b'} 
                        label="AI Probability"
                        status={aiResult.score > 40 ? 'High Likelihood' : aiResult.score > 20 ? 'Marginal Detection' : 'Human Written'}
                    />
                </div>
            </section>

            {/* Primary Intelligence Sources */}
            <section style={{ marginBottom: '48px', pageBreakInside: 'avoid' }}>
                <h3 style={{ fontSize: '11px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px', color: '#94a3b8' }}>
                    <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#0f172a' }}></span>
                    Primary Intelligence Sources
                </h3>
                <div style={{ borderRadius: '16px', overflow: 'hidden', border: '1px solid #f1f5f9', boxShadow: '0 1px 2px 0 rgba(0, 0, 0, 0.05)' }}>
                    <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse' }}>
                        <thead>
                            <tr style={{ backgroundColor: '#f8fafc', borderBottom: '1px solid #f1f5f9' }}>
                                <th style={{ padding: '16px 24px', fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#94a3b8' }}>#</th>
                                <th style={{ padding: '16px 24px', fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#94a3b8' }}>Source Origin</th>
                                <th style={{ padding: '16px 24px', fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', textAlign: 'right', color: '#94a3b8' }}>Similarity</th>
                                <th style={{ padding: '16px 24px', fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', textAlign: 'center', color: '#94a3b8' }}>Action</th>
                            </tr>
                        </thead>
                        <tbody style={{ backgroundColor: '#ffffff' }}>
                            {plagiarismResult.flaggedSentences.length > 0 ? (
                                plagiarismResult.flaggedSentences.slice(0, 5).map((source, idx) => (
                                    <tr key={idx} style={{ borderBottom: '1px solid #f8fafc' }}>
                                        <td style={{ padding: '16px 24px', fontSize: '12px', fontWeight: '900', color: '#cbd5e1' }}>{(idx + 1).toString().padStart(2, '0')}</td>
                                        <td style={{ padding: '16px 24px' }}>
                                            <div style={{ fontSize: '13px', fontWeight: '700', marginBottom: '2px', color: '#1e293b' }}>{source.source.title}</div>
                                            <div style={{ fontSize: '10px', fontWeight: '500', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', maxWidth: '300px', color: '#94a3b8' }}>{source.source.url}</div>
                                        </td>
                                        <td style={{ padding: '16px 24px', textAlign: 'right' }}>
                                            <span style={{ fontSize: '13px', fontWeight: '900', color: source.similarity > 40 ? '#ef4444' : '#f59e0b' }}>
                                                {source.similarity.toFixed(1)}%
                                            </span>
                                        </td>
                                        <td style={{ padding: '16px 24px', textAlign: 'center' }}>
                                            <HiOutlineExternalLink style={{ width: '16px', height: '16px', marginLeft: 'auto', marginRight: 'auto', color: '#cbd5e1' }} />
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan={4} style={{ padding: '32px', textAlign: 'center', fontSize: '12px', fontWeight: '500', color: '#94a3b8', fontStyle: 'italic' }}>
                                        No major matching sources detected in academic databases.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </section>

            {/* Document Analysis (Visual) */}
            <section style={{ marginBottom: '48px' }}>
                <h3 style={{ fontSize: '11px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px', color: '#94a3b8' }}>
                    <span style={{ width: '6px', height: '6px', borderRadius: '50%', backgroundColor: '#0f172a' }}></span>
                    Document Analysis (Visual)
                </h3>
                <div style={{ padding: '32px', borderRadius: '16px', minHeight: '400px', backgroundColor: 'rgba(248, 250, 252, 0.5)', border: '1px solid #f1f5f9' }}>
                    <div style={{ textAlign: 'justify', lineHeight: '1.8', fontSize: '13px', fontWeight: '400', whiteSpace: 'pre-wrap', color: '#334155' }}>
                        {aiResult.sentenceAnalysis.map((sa, i) => {
                            const plagged = plagiarismResult.flaggedSentences.find(f => 
                                f.text.toLowerCase().trim() === sa.text.toLowerCase().trim() || 
                                sa.text.includes(f.text) || 
                                f.text.includes(sa.text)
                            );

                            let highlightStyle: React.CSSProperties = { display: 'inline' };
                            if (plagged) {
                                highlightStyle = { backgroundColor: '#fdf2f2', color: '#991b1b', borderBottom: '2px solid #f87171' };
                            } else if (sa.label === 'AI') {
                                highlightStyle = { backgroundColor: '#fff7ed', color: '#9a3412', borderBottom: '2px solid #fb923c' };
                            } else if (sa.label === 'Mixed') {
                                highlightStyle = { backgroundColor: '#fefce8', color: '#854d0e', borderBottom: '2px solid #facc15' };
                            }

                            return (
                                <React.Fragment key={i}>
                                    <span style={{ 
                                        ...highlightStyle, 
                                        display: 'inline', 
                                        WebkitBoxDecorationBreak: 'clone',
                                        boxDecorationBreak: 'clone',
                                        padding: '2px 0'
                                    }}>{sa.text}</span>
                                    <span> </span>
                                </React.Fragment>
                            );
                        })}
                    </div>

                    <div style={{ marginTop: '32px', paddingTop: '24px', display: 'flex', alignItems: 'center', gap: '32px', justifyContent: 'center', borderTop: '1px solid #e2e8f0' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <span style={{ width: '10px', height: '10px', borderRadius: '2px', backgroundColor: '#fee2e2', border: '1px solid #f87171' }}></span>
                            <span style={{ fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#64748b' }}>Plagiarism Match</span>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <span style={{ width: '10px', height: '10px', borderRadius: '2px', backgroundColor: '#ffedd5', border: '1px solid #fb923c' }}></span>
                            <span style={{ fontSize: '10px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#64748b' }}>AI-Generated Content</span>
                        </div>
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer style={{ marginTop: 'auto', paddingTop: '32px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', borderTop: '1px solid #f1f5f9', pageBreakInside: 'avoid' }}>
                <div style={{ maxWidth: '320px' }}>
                    <p style={{ fontSize: '8px', fontWeight: '700', textTransform: 'uppercase', letterSpacing: '0.2em', lineHeight: '2', color: '#cbd5e1' }}>
                        Confidentiality Notice: This report is generated by ScholarAssist Analysis Engine. The contents are intended solely for the person or entity to which they are addressed. Unauthorized review is strictly prohibited.
                    </p>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '10px', fontWeight: '900', marginBottom: '4px', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#0f172a' }}>Page 01 / 01</div>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: '6px' }}>
                        <HiOutlinePresentationChartBar style={{ width: '12px', height: '12px', color: '#10b981' }} />
                        <span style={{ fontSize: '9px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '0.1em', color: '#059669' }}>Cryptographically Verified</span>
                    </div>
                </div>
            </footer>
        </div>
    );
}
